import '../models/user_model.dart';
import '../models/exam_model.dart';
import '../models/course_model.dart';
import '../models/live_class_model.dart';
import '../models/test_model.dart';
import '../models/current_affairs_model.dart';
import '../models/certificate_model.dart';
import '../models/notification_model.dart';

class MockData {
  static UserModel initialUser = UserModel(
    id: 'user_001',
    fullName: 'Vijay Gurjar',
    email: 'vijay.gurjar@example.com',
    phone: '+91 98765 43210',
    targetExam: 'SSC CGL',
    preferredLanguage: 'Bilingual (Hinglish)',
    streakDays: 12,
    totalStudyMinutes: 2450,
    averageAccuracy: 82.5,
    joinedDate: DateTime.now().subtract(const Duration(days: 45)),
  );

  static List<ExamCategoryModel> examCategories = [
    ExamCategoryModel(
      id: 'ssc_cgl',
      title: 'SSC CGL 2026',
      code: 'SSC',
      iconName: 'assignment',
      description: 'Combined Graduate Level Examination for Tier 1 & Tier 2',
      examDate: DateTime.now().add(const Duration(days: 87)),
      subjects: ['Quantitative Aptitude', 'Reasoning', 'English Language', 'General Awareness'],
      activeStudentsCount: 42000,
    ),
    ExamCategoryModel(
      id: 'upsc_cse',
      title: 'UPSC CSE 2026',
      code: 'UPSC',
      iconName: 'account_balance',
      description: 'Civil Services Prelims & Mains Complete Preparation',
      examDate: DateTime.now().add(const Duration(days: 142)),
      subjects: ['GS Paper I', 'CSAT Paper II', 'Current Affairs', 'Essay & Answer Writing'],
      activeStudentsCount: 65000,
    ),
    ExamCategoryModel(
      id: 'raj_police',
      title: 'Rajasthan Police Constable & SI',
      code: 'RAJ_POL',
      iconName: 'security',
      description: 'Complete syllabus coverage with Rajasthan Special GK',
      examDate: DateTime.now().add(const Duration(days: 54)),
      subjects: ['Reasoning & Computer', 'Rajasthan History & Culture', 'General Science', 'Indian Law'],
      activeStudentsCount: 28000,
    ),
    ExamCategoryModel(
      id: 'banking_ibps',
      title: 'Banking (IBPS PO & Clerk)',
      code: 'BANK',
      iconName: 'account_balance_wallet',
      description: 'Bank PO & Clerk Prelims + Mains Foundation Batch',
      examDate: DateTime.now().add(const Duration(days: 70)),
      subjects: ['Data Interpretation', 'Logical Reasoning', 'English', 'Financial Awareness'],
      activeStudentsCount: 35000,
    ),
    ExamCategoryModel(
      id: 'railway_rrb',
      title: 'Railway RRB NTPC & Group D',
      code: 'RRB',
      iconName: 'train',
      description: 'CBT 1 & CBT 2 Comprehensive Preparation',
      examDate: DateTime.now().add(const Duration(days: 110)),
      subjects: ['Mathematics', 'General Intelligence', 'General Science', 'General Awareness'],
      activeStudentsCount: 50000,
    ),
    ExamCategoryModel(
      id: 'agri_super',
      title: 'Agriculture Supervisor',
      code: 'AGRI',
      iconName: 'agriculture',
      description: 'Rajasthan Agriculture Supervisor Special Course',
      examDate: DateTime.now().add(const Duration(days: 62)),
      subjects: ['Agriculture Science', 'Horticulture', 'Animal Husbandry', 'Hindi & Raj GK'],
      activeStudentsCount: 18000,
    ),
    ExamCategoryModel(
      id: 'ca_foundation',
      title: 'CA Foundation & Inter',
      code: 'CA',
      iconName: 'calculate',
      description: 'ICAI Syllabus accounting, business laws & quantitative aptitude',
      examDate: DateTime.now().add(const Duration(days: 95)),
      subjects: ['Accounting', 'Business Laws', 'Quantitative Aptitude', 'Business Economics'],
      activeStudentsCount: 22000,
    ),
  ];

  static List<CourseModel> courses = [
    CourseModel(
      id: 'c_ssc_quant_01',
      title: 'SSC CGL Complete Quantitative Aptitude Masterclass',
      examCategory: 'SSC CGL 2026',
      instructorName: 'Abhinav Sharma',
      instructorRole: 'Ex-Income Tax Inspector & Math Wizard',
      rating: 4.9,
      ratingCount: 1240,
      studentCount: 18500,
      durationText: '120+ Hours',
      price: 1499.0,
      originalPrice: 3999.0,
      courseType: CourseType.paid,
      thumbnailUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600&q=80',
      description: 'Comprehensive coverage of Advanced Mathematics & Arithmetic short tricks tailored specifically for SSC CGL Tier 1 & Tier 2.',
      whatYouWillLearn: [
        'Master Percentage, Profit & Loss, Ratio & Proportion',
        'Advanced Geometry, Trigonometry, and Mensuration shortcuts',
        'Data Interpretation speed calculation tricks',
        'Solve previous 10 years CGL questions in under 30 seconds'
      ],
      totalLessons: 30,
      completedLessonsCount: 18,
      isEnrolled: true,
      progressPercentage: 0.72,
      lastLessonTitle: 'Lesson 18: Percentage Advanced Concepts & Short Tricks',
      chapters: [
        ChapterModel(
          id: 'ch_01',
          title: 'Chapter 1: Percentage & Applications',
          lessons: [
            LessonModel(
              id: 'l_01',
              chapterId: 'ch_01',
              title: 'Lesson 01: Basics of Percentage & Fraction Conversion',
              durationText: '28:45',
              durationSeconds: 1725,
              videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
              pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
              isFreeDemo: true,
              isCompleted: true,
            ),
            LessonModel(
              id: 'l_02',
              chapterId: 'ch_01',
              title: 'Lesson 02: Successive Percentage Change & Formulas',
              durationText: '34:10',
              durationSeconds: 2050,
              videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
              pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
              isFreeDemo: true,
              isCompleted: true,
            ),
            LessonModel(
              id: 'l_18',
              chapterId: 'ch_01',
              title: 'Lesson 18: Percentage Advanced Concepts & Short Tricks',
              durationText: '42:15',
              durationSeconds: 2535,
              videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
              pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
              isFreeDemo: false,
              isCompleted: false,
              watchPositionSeconds: 1800,
            ),
          ],
        ),
        ChapterModel(
          id: 'ch_02',
          title: 'Chapter 2: Profit, Loss & Discount',
          lessons: [
            LessonModel(
              id: 'l_19',
              chapterId: 'ch_02',
              title: 'Lesson 19: Marked Price, Cost Price & Discount Equations',
              durationText: '38:00',
              durationSeconds: 2280,
              videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
              isFreeDemo: false,
              isCompleted: false,
            ),
          ],
        ),
      ],
    ),
    CourseModel(
      id: 'c_upsc_gs1',
      title: 'UPSC GS Paper I - Indian Polity & Governance',
      examCategory: 'UPSC CSE 2026',
      instructorName: 'Dr. Rajesh Verma',
      instructorRole: 'Retired IAS & Senior Faculty',
      rating: 4.95,
      ratingCount: 3100,
      studentCount: 29000,
      durationText: '180+ Hours',
      price: 2999.0,
      originalPrice: 7999.0,
      courseType: CourseType.paid,
      thumbnailUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&q=80',
      description: 'Complete Indian Polity and Constitutional framework breakdown based on Laxmikanth with Mains Answer Writing focus.',
      whatYouWillLearn: [
        'Fundamental Rights, Directive Principles, Fundamental Duties',
        'Structure of Executive, Legislature & Judiciary',
        'Constitutional & Non-Constitutional Bodies',
        'Mains Answer Writing framework for Polity questions'
      ],
      totalLessons: 45,
      completedLessonsCount: 10,
      isEnrolled: true,
      progressPercentage: 0.22,
      lastLessonTitle: 'Lesson 10: Preamble & Constitutional Values',
      chapters: [
        ChapterModel(
          id: 'ch_pol_01',
          title: 'Chapter 1: Historical Background & Making of Constitution',
          lessons: [
            LessonModel(
              id: 'l_pol_01',
              chapterId: 'ch_pol_01',
              title: 'Lesson 01: Regulating Act 1773 to Government of India Act 1935',
              durationText: '50:12',
              durationSeconds: 3012,
              videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
              pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
              isFreeDemo: true,
              isCompleted: true,
            ),
          ],
        ),
      ],
    ),
    CourseModel(
      id: 'c_raj_gk_01',
      title: 'Rajasthan GK Foundation Special - History, Culture & Geography',
      examCategory: 'Rajasthan Police Constable & SI',
      instructorName: 'Subhash Charan Sir',
      instructorRole: 'Rajasthan GK Expert',
      rating: 4.98,
      ratingCount: 5400,
      studentCount: 41000,
      durationText: '90 Hours',
      price: 0.0,
      originalPrice: 1999.0,
      courseType: CourseType.free,
      thumbnailUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80',
      description: 'Complete free foundation course covering Rajasthan History, Forts, Architecture, Folk Art, and Geography.',
      whatYouWillLearn: [
        'Mewar, Marwar, and Jaipur Royal Dynasties',
        'Rajasthan Forts, UNESCO Heritage sites, and Culture',
        'Rivers, Soil, Wildlife Sanctuaries of Rajasthan',
        'Targeted for Police Constable, SI & Agriculture Supervisor'
      ],
      totalLessons: 25,
      completedLessonsCount: 0,
      isEnrolled: false,
      progressPercentage: 0.0,
      chapters: [
        ChapterModel(
          id: 'ch_raj_01',
          title: 'Chapter 1: Forts and Architecture of Rajasthan',
          lessons: [
            LessonModel(
              id: 'l_raj_01',
              chapterId: 'ch_raj_01',
              title: 'Lesson 01: Chittorgarh & Kumbhalgarh Forts Deep Dive',
              durationText: '40:15',
              durationSeconds: 2415,
              videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
              pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
              isFreeDemo: true,
              isCompleted: false,
            ),
          ],
        ),
      ],
    ),
    CourseModel(
      id: 'c_demo_reasoning',
      title: 'Demo Class: Logical & Analytical Reasoning Short Tricks',
      examCategory: 'SSC CGL 2026',
      instructorName: 'Vikramjeet Sir',
      instructorRole: 'Reasoning Specialist',
      rating: 4.88,
      ratingCount: 890,
      studentCount: 15000,
      durationText: '5 Hours Free Demo',
      price: 0.0,
      originalPrice: 999.0,
      courseType: CourseType.demo,
      thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80',
      description: 'Try out our top-rated reasoning class demo for free. Includes syllogism tricks, coding-decoding, and blood relations.',
      whatYouWillLearn: [
        '10-Second Syllogism Venn Diagram Trick',
        'Matrix Coding & Series Completion Patterns',
        'Seating Arrangement Speed Strategies'
      ],
      totalLessons: 5,
      completedLessonsCount: 2,
      isEnrolled: true,
      progressPercentage: 0.40,
      lastLessonTitle: 'Lesson 2: Syllogism 100/50 Rule Demystified',
      chapters: [
        ChapterModel(
          id: 'ch_rs_01',
          title: 'Demo Chapter: Essential Tricks',
          lessons: [
            LessonModel(
              id: 'l_rs_01',
              chapterId: 'ch_rs_01',
              title: 'Lesson 01: Coding-Decoding Letter Index Shortcuts',
              durationText: '25:00',
              durationSeconds: 1500,
              videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
              isFreeDemo: true,
              isCompleted: true,
            ),
          ],
        ),
      ],
    ),
  ];

  static List<LiveClassModel> liveClasses = [
    LiveClassModel(
      id: 'live_01',
      title: '🔴 LIVE: Daily Current Affairs & Editorial Analysis - Aug 19',
      subject: 'Current Affairs',
      courseTitle: 'UPSC CSE 2026 Masterclass',
      instructorName: 'Deepak Yadav Sir',
      scheduledAt: DateTime.now(),
      durationText: '60 Mins',
      isLiveNow: true,
      activeViewers: 3420,
      type: LiveType.liveClass,
    ),
    LiveClassModel(
      id: 'live_02',
      title: 'Live Doubt Solving: Geometry & Circle Theorems',
      subject: 'Quantitative Aptitude',
      courseTitle: 'SSC CGL Complete Batch',
      instructorName: 'Abhinav Sharma',
      scheduledAt: DateTime.now().add(const Duration(hours: 3)),
      durationText: '45 Mins',
      isUpcoming: true,
      reminderSet: true,
      type: LiveType.doubtSession,
    ),
    LiveClassModel(
      id: 'live_03',
      title: 'Scheduled Live Mock Test: All India SSC CGL Tier 1 Mini Mock',
      subject: 'Full Mock Test',
      courseTitle: 'All India Test Series',
      instructorName: 'Pariksha Exam Panel',
      scheduledAt: DateTime.now().add(const Duration(hours: 6)),
      durationText: '60 Mins',
      isUpcoming: true,
      type: LiveType.liveTest,
    ),
  ];

  static List<TestSeriesModel> testSeries = [
    TestSeriesModel(
      id: 'ts_ssc_mock_01',
      title: 'SSC CGL Tier 1 All India Full Mock Test 05',
      examCategory: 'SSC CGL 2026',
      category: TestCategory.fullMock,
      totalQuestions: 100,
      durationMinutes: 60,
      totalMarks: 200.0,
      negativeMarks: 0.5,
      attemptsCount: 14200,
      isFree: true,
    ),
    TestSeriesModel(
      id: 'ts_ssc_quant_ch1',
      title: 'Quantitative Aptitude - Percentage Chapter Test',
      examCategory: 'SSC CGL 2026',
      category: TestCategory.chapterTest,
      totalQuestions: 25,
      durationMinutes: 20,
      totalMarks: 50.0,
      negativeMarks: 0.5,
      attemptsCount: 8900,
      isFree: true,
    ),
    TestSeriesModel(
      id: 'ts_upsc_polity',
      title: 'UPSC Prelims GS 1 - Indian Polity Subject Test',
      examCategory: 'UPSC CSE 2026',
      category: TestCategory.subjectTest,
      totalQuestions: 50,
      durationMinutes: 60,
      totalMarks: 100.0,
      negativeMarks: 0.66,
      attemptsCount: 6700,
      isFree: false,
    ),
  ];

  static List<TestQuestionModel> sampleMockQuestions = [
    const TestQuestionModel(
      id: 'q_01',
      questionText: 'If the price of sugar increases by 20%, by what percentage should a household reduce its consumption so that the expenditure remains constant?',
      options: ['16.67%', '20%', '15%', '25%'],
      correctOptionIndex: 0,
      explanation: 'Let initial price = 100. New price = 120. Reduction required = (20 / 120) * 100 = 16.67%.',
      subject: 'Quantitative Aptitude',
      topic: 'Percentage',
    ),
    const TestQuestionModel(
      id: 'q_02',
      questionText: 'Which Article of the Constitution of India guarantees the Right to Equality before Law?',
      options: ['Article 12', 'Article 14', 'Article 19', 'Article 21'],
      correctOptionIndex: 1,
      explanation: 'Article 14 guarantees equality before law and equal protection of laws to all persons within the territory of India.',
      subject: 'General Awareness',
      topic: 'Indian Polity',
    ),
    const TestQuestionModel(
      id: 'q_03',
      questionText: 'Select the related word from the given alternatives: Thermometer : Temperature :: Barometer : ?',
      options: ['Humidity', 'Pressure', 'Wind Speed', 'Thickness'],
      correctOptionIndex: 1,
      explanation: 'Thermometer measures Temperature; Barometer measures Atmospheric Pressure.',
      subject: 'Reasoning',
      topic: 'Analogy',
    ),
    const TestQuestionModel(
      id: 'q_04',
      questionText: 'Select the correctly spelt word:',
      options: ['Accommodation', 'Acommodation', 'Accomodation', 'Acomodation'],
      correctOptionIndex: 0,
      explanation: 'The correct spelling is "Accommodation" with double \'c\' and double \'m\'.',
      subject: 'English Language',
      topic: 'Spelling Check',
    ),
    const TestQuestionModel(
      id: 'q_05',
      questionText: 'In Rajasthan, which fort is known as the "Golden Fort" or Sonar Qila?',
      options: ['Mehrangarh Fort', 'Jaisalmer Fort', 'Amer Fort', 'Taragarh Fort'],
      correctOptionIndex: 1,
      explanation: 'Jaisalmer Fort, built of yellow sandstone on Trikuta Hill, is famous as Sonar Qila (Golden Fort).',
      subject: 'General Awareness',
      topic: 'Rajasthan History & Forts',
    ),
  ];

  static TestAttemptModel recentTestResult = TestAttemptModel(
    id: 'attempt_99',
    testId: 'ts_ssc_mock_01',
    testTitle: 'SSC CGL Tier 1 All India Full Mock Test 04',
    score: 154.5,
    maxScore: 200.0,
    percentage: 77.25,
    accuracy: 88.5,
    correctCount: 80,
    incorrectCount: 10,
    unattemptedCount: 10,
    timeSpentSeconds: 3240,
    rank: 412,
    subjectPerformance: {
      'Quantitative Aptitude': 44.0,
      'Reasoning': 48.0,
      'English Language': 38.5,
      'General Awareness': 24.0,
    },
    weakTopics: ['General Awareness (Current Schemes)', 'English (Active/Passive Voice)'],
    strongTopics: ['Reasoning (Syllogism)', 'Quantitative Aptitude (Algebra & Geometry)'],
    completedAt: DateTime.now().subtract(const Duration(days: 2)),
  );

  static List<CurrentAffairsModel> currentAffairs = [
    CurrentAffairsModel(
      id: 'ca_01',
      title: 'India Launches Unified Digital Public Infrastructure Program for Agriculture',
      category: 'National',
      summary: 'The Union Cabinet has approved an outlay for the AgriStack and Digital General Crop Estimation Survey.',
      keyTakeaways: [
        'Farmers will receive unique Farmer IDs linked to land records',
        'Enables direct benefit transfer and accurate crop loss assessments',
        'High exam relevance for UPSC GS 3 & SSC General Awareness'
      ],
      examRelevance: 'UPSC GS 3 (Agriculture & Technology) / SSC CGL GA',
      publishedDate: DateTime.now(),
      imageUrl: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=600&q=80',
    ),
    CurrentAffairsModel(
      id: 'ca_02',
      title: 'Rajasthan Government Expands Chief Minister Chiranjeevi Health Insurance Scheme',
      category: 'Rajasthan GK',
      summary: 'Coverage extended for specialized tertiary treatments across all district government hospitals.',
      keyTakeaways: [
        'Enhanced cashless insurance cover per family per year',
        'Covers organ transplants and oncology procedures',
        'Crucial for Rajasthan Police, SI & Agriculture Supervisor Exams'
      ],
      examRelevance: 'Rajasthan State Exams / RAS / Police Constable',
      publishedDate: DateTime.now().subtract(const Duration(days: 1)),
      imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&q=80',
    ),
  ];

  static List<CertificateModel> certificates = [
    CertificateModel(
      id: 'cert_01',
      certificateNumber: 'PRK-2026-8841',
      courseTitle: 'SSC CGL Mathematics Mastery Batch',
      studentName: 'Vijay Gurjar',
      issueDate: DateTime.now().subtract(const Duration(days: 10)),
      verificationUrl: 'https://parikshaprep.com/verify/PRK-2026-8841',
    ),
  ];

  static List<NotificationModel> notifications = [
    NotificationModel(
      id: 'notif_01',
      title: '🔴 Live Class Started!',
      message: 'Deepak Yadav Sir is live now on Daily Current Affairs & Editorial Analysis.',
      timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
      type: NotificationType.liveClass,
      route: '/live',
    ),
    NotificationModel(
      id: 'notif_02',
      title: '📊 Weekly Test Result Published',
      message: 'Your score for SSC CGL Tier 1 Mock 04 is 154.5/200. Rank: 412.',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      type: NotificationType.testResult,
      route: '/test-result',
    ),
    NotificationModel(
      id: 'notif_03',
      title: '📖 New Notes Uploaded',
      message: 'PDF notes for Percentage Short Tricks are now available in your enrolled course.',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      type: NotificationType.courseUpdate,
      route: '/my-learning',
    ),
  ];
}
